### ISSUE TITLE
At most once semantics

### ISSUE THREAD

**Issue by jordan-heemskerk** [jordan-heemskerk/csc-462#38]
We need to generate a UID for each request in the client, and then check it on the server so that we know we are not duplicating. Just like in Lab 2.

**Comment by eburdon** [comment]
hmm... so similar set up as the original PAXOS? We have the sequential number we maintain to start the whole thing, then have a timestamp?

**Comment by jordan-heemskerk** [comment]
Well, similar setup to the original keyvalue server... We should generate a uint64 randomly before we send requests and include it as part of the operation. Then we keep track of which ones we have already dealt with in the server and don't apply anything that we already have. This could actually fix some issues.

**Comment by jordan-heemskerk** [comment]
It's like this (on assignment2 tag) https://github.com/jordan-heemskerk/csc-462/blob/assignment2/src/pbservice/client.go#L140 

And then we keep track on the server of what we have done https://github.com/jordan-heemskerk/csc-462/blob/assignment2/src/pbservice/server.go#L30
