### ISSUE TITLE
Adjust preprocessing

### ISSUE THREAD

**Issue by jordan-heemskerk** [jordan-heemskerk/csc-462#4]
Need to output

```
NAME;DATE
NAME;DATE
...
```

for each line so that we can keep track of people

**Comment by jordan-heemskerk** [comment]
Here's a question: how does the XML handle group conversations and how do we want to handle that case?

**Comment by eburdon** [comment]
hmm. I think the thread block just lists the other people in the conversation. E.g., 
`<thread>Bobby Green, Susan Hill, Adam Sandler</thread>`

But I'm not sure it makes sense - this is more so comparing individuals...
