### ISSUE TITLE
Adjust post-processing

### ISSUE THREAD

**Issue by jordan-heemskerk** [jordan-heemskerk/csc-462#7]
Update the post processor to read the new data format
1. Sort by the number of messages
2. Import prefix trees for top results (3 of them?) 
3. Generate a visualization of a histogram using the prefix tree of the top results

**Comment by eburdon** [comment]
Pick your graph (since apparently I make poor visual choices)

https://github.com/vdobler/chart

**Comment by jordan-heemskerk** [comment]
I think "Stacked Histograms" would be perfect for this! Each top person can have a different stacked histogram!

EDIT: Each top person can have a different "Sample" as in the example, not an entirely different plot. That may have been confusing

**Comment by eburdon** [comment]
Sure!

**Comment by jordan-heemskerk** [comment]
Addressed by #13
